/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  IBodyRow,
} from './components/table-body-row/IBodyRow';
import {
  IHeaderColumn,
} from './components/table-header-cell/IHeaderColumn';
import {
  EventEmitter,
} from '@stencil/core';
import {
  IOnSortChange,
} from './components/table-header-cell/IOnSortChange';


export namespace Components {

  interface SflTableBodyCell {
    'value': string;
  }
  interface SflTableBodyCellAttributes extends StencilHTMLAttributes {
    'value': string;
  }

  interface SflTableBodyRow {
    'row': IBodyRow;
  }
  interface SflTableBodyRowAttributes extends StencilHTMLAttributes {
    'row': IBodyRow;
  }

  interface SflTableHeaderCell {
    'column': IHeaderColumn;
    'key': number;
    'sortable': boolean;
  }
  interface SflTableHeaderCellAttributes extends StencilHTMLAttributes {
    'column': IHeaderColumn;
    'key': number;
    'onOnSortChange'?: (event: CustomEvent<IOnSortChange>) => void;
    'sortable'?: boolean;
  }

  interface SflTableHeaderRow {
    'columns': Array<IHeaderColumn>;
  }
  interface SflTableHeaderRowAttributes extends StencilHTMLAttributes {
    'columns'?: Array<IHeaderColumn>;
  }

  interface SflTable {
    'noResults': boolean;
  }
  interface SflTableAttributes extends StencilHTMLAttributes {
    'noResults'?: boolean;
  }
}

declare global {
  interface StencilElementInterfaces {
    'SflTableBodyCell': Components.SflTableBodyCell;
    'SflTableBodyRow': Components.SflTableBodyRow;
    'SflTableHeaderCell': Components.SflTableHeaderCell;
    'SflTableHeaderRow': Components.SflTableHeaderRow;
    'SflTable': Components.SflTable;
  }

  interface StencilIntrinsicElements {
    'sfl-table-body-cell': Components.SflTableBodyCellAttributes;
    'sfl-table-body-row': Components.SflTableBodyRowAttributes;
    'sfl-table-header-cell': Components.SflTableHeaderCellAttributes;
    'sfl-table-header-row': Components.SflTableHeaderRowAttributes;
    'sfl-table': Components.SflTableAttributes;
  }


  interface HTMLSflTableBodyCellElement extends Components.SflTableBodyCell, HTMLStencilElement {}
  var HTMLSflTableBodyCellElement: {
    prototype: HTMLSflTableBodyCellElement;
    new (): HTMLSflTableBodyCellElement;
  };

  interface HTMLSflTableBodyRowElement extends Components.SflTableBodyRow, HTMLStencilElement {}
  var HTMLSflTableBodyRowElement: {
    prototype: HTMLSflTableBodyRowElement;
    new (): HTMLSflTableBodyRowElement;
  };

  interface HTMLSflTableHeaderCellElement extends Components.SflTableHeaderCell, HTMLStencilElement {}
  var HTMLSflTableHeaderCellElement: {
    prototype: HTMLSflTableHeaderCellElement;
    new (): HTMLSflTableHeaderCellElement;
  };

  interface HTMLSflTableHeaderRowElement extends Components.SflTableHeaderRow, HTMLStencilElement {}
  var HTMLSflTableHeaderRowElement: {
    prototype: HTMLSflTableHeaderRowElement;
    new (): HTMLSflTableHeaderRowElement;
  };

  interface HTMLSflTableElement extends Components.SflTable, HTMLStencilElement {}
  var HTMLSflTableElement: {
    prototype: HTMLSflTableElement;
    new (): HTMLSflTableElement;
  };

  interface HTMLElementTagNameMap {
    'sfl-table-body-cell': HTMLSflTableBodyCellElement
    'sfl-table-body-row': HTMLSflTableBodyRowElement
    'sfl-table-header-cell': HTMLSflTableHeaderCellElement
    'sfl-table-header-row': HTMLSflTableHeaderRowElement
    'sfl-table': HTMLSflTableElement
  }

  interface ElementTagNameMap {
    'sfl-table-body-cell': HTMLSflTableBodyCellElement;
    'sfl-table-body-row': HTMLSflTableBodyRowElement;
    'sfl-table-header-cell': HTMLSflTableHeaderCellElement;
    'sfl-table-header-row': HTMLSflTableHeaderRowElement;
    'sfl-table': HTMLSflTableElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
